server:
  config:
    logLevel: "debug,info"

    numHistoryShards: 512

    persistence:
      default:
        driver: "cassandra"

#        faultInjection:
#          targets:
#            dataStores:
#              ExecutionStore:
#                methods:
#                  GetCurrentExecution:
#                    errors:
#                      ResourceExhausted: 0.1
#                  AppendHistoryNodes:
#                    errors:
#                      ResourceExhausted: 0.05
#                  UpdateWorkflowExecution:
#                    errors:
#                      ResourceExhausted: 0.15
#                  GetWorkflowExecution:
#                    errors:
#                      ResourceExhausted: 0.15

        cassandra:
          hosts: ["cache-service-db-cassandra.default.svc.cluster.local"]
          port: 9042
          keyspace: temporal
          user: "cassandra"
          password: "VZxp0WEMaB"
          existingSecret: ""
          replicationFactor: 1
          consistency:
            default:
              consistency: "local_quorum"
              serialConsistency: "local_serial"

cassandra:
  enabled: true

mysql:
  enabled: false

postgresql:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false
elasticsearch:
  enabled: true

schema:
  createDatabase:
    enabled: true
  setup:
    enabled: true
  update:
    enabled: true
